export type CountryName = "Pakistan" | "Jordan";

export type PakistanProvinceName =
  | "Sindh"
  | "Punjab"
  | "Khyber Pakhtunkhwa"
  | "Balochistan"
  | "Islamabad Capital Territory"
  | "Azad Jammu & Kashmir"
  | "Gilgit-Baltistan";

export type JordanProvinceName =
  | "Amman Governorate"
  | "Zarqa Governorate"
  | "Irbid Governorate"
  | "Aqaba Governorate"
  | "Madaba Governorate"
  | "Balqa Governorate"
  | "Jerash Governorate"
  | "Ajloun Governorate"
  | "Karak Governorate"
  | "Ma'an Governorate"
  | "Mafraq Governorate"
  | "Tafilah Governorate";

export type ProvinceName = PakistanProvinceName | JordanProvinceName;

/** Strip BOM / odd whitespace from .env and API values. */
export function normalizeLocationString(
  raw: string | null | undefined
): string {
  return (raw ?? "")
    .replace(/^\uFEFF/, "")
    .replace(/\u00a0/g, " ")
    .trim();
}

/** Match API / user strings to a valid `CountryName` (trim, case-insensitive). */
export function parseCountryName(
  raw: string | null | undefined
): CountryName | null {
  const t = normalizeLocationString(String(raw)).toLowerCase();
  if (t === "jordan" || t === "jo" || t === "jor") {
    return "Jordan";
  }
  if (t === "pakistan" || t === "pk" || t === "pak") {
    return "Pakistan";
  }
  return null;
}

/**
 * Static location data for Pakistan and Jordan.
 * Provinces/governorates mapped to their cities.
 */
export const LOCATION_DATA: {
  Pakistan: Record<PakistanProvinceName, string[]>;
  Jordan: Record<JordanProvinceName, string[]>;
} = {
  Pakistan: {
    Sindh: [
      "Karachi",
      "Hyderabad",
      "Sukkur",
      "Larkana",
      "Nawabshah",
      "Mirpur Khas",
      "Jacobabad",
      "Shikarpur",
      "Khairpur",
      "Dadu",
      "Thatta",
      "Badin",
      "Sanghar",
      "Umerkot",
      "Matiari",
      "Jamshoro",
      "Tando Adam",
      "Tando Allahyar",
      "Ghotki",
      "Kashmore",
      "Qambar",
      "Shahdadkot",
      "Kandhkot",
      "Kotri",
      "Hala",
      "Tando Muhammad Khan",
      "Digri",
      "Mithi",
      "Chachro",
      "Islamkot",
      "Naushahro Feroze",
      "Mehrabpur",
      "Daharki",
      "Ubauro",
      "Pano Aqil",
      "Ratodero",
      "Dokri",
      "Sehwan",
      "Manjhand",
      "Gharo",
      "Mirpur Bathoro",
      "Johi",
      "Mehar",
      "Khipro",
      "Naukot",
      "Kunri",
      "Diplo",
      "Dahanu",
      "Sujawal",
      "Jati",
      "Shah Bandar",
      "Keti Bandar",
      "Karachi South",
      "Malir",
      "Korangi",
      "Landhi",
      "Orangi",
      "Baldia",
      "Lyari",
      "Saddar",
      "Clifton",
      "Gulshan-e-Iqbal",
      "Nazimabad",
      "North Nazimabad",
      "Federal B Area",
      "Site",
      "Kemari",
      "Gadap",
    ],
    Punjab: [
      "Lahore",
      "Faisalabad",
      "Rawalpindi",
      "Gujranwala",
      "Multan",
      "Sialkot",
      "Bahawalpur",
      "Sargodha",
      "Sheikhupura",
      "Jhang",
      "Rahim Yar Khan",
      "Gujrat",
      "Kasur",
      "Sahiwal",
      "Okara",
      "Dera Ghazi Khan",
      "Chiniot",
      "Hafizabad",
      "Mandi Bahauddin",
      "Jhelum",
      "Sadiqabad",
      "Khanewal",
      "Pakpattan",
      "Muzaffargarh",
      "Attock",
      "Chakwal",
      "Narowal",
      "Vehari",
      "Mianwali",
      "Bhakkar",
      "Layyah",
      "Lodhran",
      "Khushab",
      "Nankana Sahib",
      "Toba Tek Singh",
      "Murree",
      "Taxila",
      "Wah Cantonment",
      "Kamra",
      "Gujar Khan",
      "Kahuta",
      "Fateh Jang",
      "Pindi Gheb",
      "Talagang",
      "Khewra",
      "Quaidabad",
      "Kallar Kahar",
      "Lilla",
      "Kot Addu",
      "Alipur",
      "Rojhan",
      "Rajanpur",
      "Jampur",
      "Fazilpur",
      "Chowk Sarwar Shaheed",
      "Liaquatpur",
      "Khanpur",
      "Ahmadpur East",
      "Hasilpur",
      "Chishtian",
      "Yazman",
      "Fort Abbas",
      "Bahawalnagar",
      "Minchinabad",
      "Haroonabad",
      "Burewala",
      "Mailsi",
      "Kamalia",
      "Gojra",
      "Samundri",
      "Tandlianwala",
      "Jaranwala",
      "Chichawatni",
      "Arifwala",
      "Renala Khurd",
      "Depalpur",
      "Chunian",
      "Patoki",
      "Phool Nagar",
      "Muridke",
      "Narang Mandi",
      "Ferozewala",
      "Kot Abdul Malik",
      "Raiwind",
      "Manga Mandi",
      "Pattoki",
      "Daska",
      "Sambrial",
      "Wazirabad",
      "Kamoke",
      "Nowshera Virkan",
      "Kharian",
      "Lala Musa",
      "Sarai Alamgir",
      "Phalia",
      "Malikwal",
      "Sohawa",
      "Dina",
      "Mangla",
      "Pind Dadan Khan",
      "Naushahra Virkan",
      "Kot Momin",
      "Bhalwal",
      "Sahiwal (Sargodha)",
      "Sillanwali",
      "Bhera",
      "Shahpur",
      "Joharabad",
      "Kundian",
      "Piplan",
      "Wan Bhachran",
      "Darya Khan",
      "Kot Adu",
      "Muzaffargarh City",
      "Alipur Chatha",
      "Shorkot",
      "Ahmed Nager Chatha",
    ],
    "Khyber Pakhtunkhwa": [
      "Peshawar",
      "Mardan",
      "Mingora",
      "Kohat",
      "Abbottabad",
      "Mansehra",
      "Dera Ismail Khan",
      "Swabi",
      "Nowshera",
      "Charsadda",
      "Bannu",
      "Haripur",
      "Karak",
      "Lakki Marwat",
      "Hangu",
      "Tank",
      "Batagram",
      "Chitral",
      "Dir (Upper)",
      "Dir (Lower)",
      "Shangla",
      "Buner",
      "Malakand",
      "Kohistan",
      "Naran",
      "Kaghan",
      "Balakot",
      "Shinkiari",
      "Oghi",
      "Torghar",
      "Kolai-Pallas",
      "Daggar",
      "Alpuri",
      "Besham",
      "Dasu",
      "Pattan",
      "Komila",
      "Chakdara",
      "Timergara",
      "Saidu Sharif",
      "Matta",
      "Bahrain",
      "Madyan",
      "Kalam",
      "Aseret",
      "Drosh",
      "Mastuj",
      "Booni",
      "Garam Chashma",
      "Ayun",
      "Buni",
      "Bumburet",
      "Rumbur",
      "Birir",
      "Shishi",
      "Arandu",
      "Phandu",
      "Parachinar",
      "Sadda",
      "Alizai",
      "Wana",
      "Birmal",
      "Shakai",
      "Ladha",
      "Makin",
      "Sararogha",
      "Jandola",
      "Kulachi",
      "Daraban",
      "Yarik",
      "Paroa",
      "Gomal",
      "Pezu",
      "Lachi",
      "Togh",
      "Banda Daud Shah",
      "Thal (Hangu)",
      "Doaba",
      "Ustarzai",
      "Kamar Mushani",
      "Takht-e-Nasrati",
      "Risalpur",
      "Jehangira",
      "Topi",
      "Lundkhwar",
      "Barikot",
      "Kabal",
      "Matta",
      "Khwazakhela",
      "Charbagh",
      "Shamozai",
      "Fatehpur",
      "Mian Gujjar",
      "Rustam",
      "Yar Hussain",
      "Zaida",
      "Razar",
      "Katlang",
      "Takht Bhai",
      "Hund",
      "Garhi Kapura",
      "Pabbi",
      "Akbarpura",
      "Umarzai",
      "Tangi",
      "Shabqadar",
      "Michni",
      "Nisatta",
      "Utmanzai",
      "Prang Ghar",
      "Sherpao",
      "Charsadda City",
      "Spin Khal",
      "Mattani",
      "Chamkani",
      "Hayatabad",
      "Dalazak",
      "Nahaqi",
      "Sheikhan",
      "Landi Kotal",
      "Bara",
      "Jamrud",
      "Ali Masjid",
      "Torkham",
      "Landi Khana",
    ],
    Balochistan: [
      "Quetta",
      "Turbat",
      "Khuzdar",
      "Chaman",
      "Hub",
      "Sibi",
      "Zhob",
      "Gwadar",
      "Dera Murad Jamali",
      "Loralai",
      "Panjgur",
      "Nushki",
      "Kalat",
      "Mastung",
      "Kharan",
      "Washuk",
      "Awaran",
      "Kech",
      "Bolan",
      "Nasirabad",
      "Jafferabad",
      "Lasbela",
      "Usta Muhammad",
      "Dera Allah Yar",
      "Gandakha",
      "Sui",
      "Dera Bugti",
      "Kohlu",
      "Barkhan",
      "Musakhel",
      "Ziarat",
      "Pishin",
      "Qilla Abdullah",
      "Kuchlak",
      "Gulistan",
      "Qilla Saifullah",
      "Muslimbagh",
      "Qila Abdullah",
      "Dalbandin",
      "Nokundi",
      "Chaghi",
      "Taftan",
      "Nok Kundi",
      "Basima",
      "Surab",
      "Khad Kocha",
      "Wadh",
      "Ornach",
      "Uthal",
      "Bela",
      "Sonmiani",
      "Ormara",
      "Pasni",
      "Jiwani",
      "Pishukan",
      "Mand",
      "Hoshab",
      "Tump",
      "Nag",
      "Saindak",
      "Reko Diq",
      "Besima",
      "Kharan City",
      "Sanjawi",
      "Duki",
      "Harnai",
      "Shahrig",
      "Spezand",
      "Pishin City",
      "Khanozai",
      "Haramzai",
      "Karezat",
      "Zarghoon",
    ],
    "Islamabad Capital Territory": [
      "Islamabad",
      "Rawat",
      "Kahuta (ICT)",
      "Noon",
      "Sihala",
      "Phulgran",
      "Tarlai",
      "Bhara Kahu",
      "Bani Gala",
      "Golra",
      "Humak",
      "Lethrar",
      "Kirpa",
      "Pind Begwal",
      "Shahdara",
    ],
    "Azad Jammu & Kashmir": [
      "Muzaffarabad",
      "Mirpur",
      "Rawalakot",
      "Bagh",
      "Kotli",
      "Bhimber",
      "Plandri",
      "Pallandri",
      "Sudhnoti",
      "Haveli",
      "Hattian Bala",
      "Neelum",
      "Sharda",
      "Kel",
      "Athmuqam",
      "Leepa",
      "Taobat",
      "Dawarian",
      "Keran",
      "Halmat",
      "Forward Kahuta",
      "Samahni",
      "Barnala",
      "Sehnsa",
      "Charhoi",
      "Dadyal",
      "Chakswari",
      "Mangla",
      "Dudyal",
      "Nakyal",
    ],
    "Gilgit-Baltistan": [
      "Gilgit",
      "Skardu",
      "Hunza",
      "Chilas",
      "Ghizer",
      "Astore",
      "Kharmang",
      "Shigar",
      "Roundu",
      "Ganche",
      "Khaplu",
      "Hushe",
      "Dansam",
      "Chorbat",
      "Saltoro",
      "Karimabad",
      "Aliabad",
      "Ganish",
      "Nagar",
      "Minapin",
      "Hopar",
      "Passu",
      "Gulmit",
      "Ghulkin",
      "Sost",
      "Misgar",
      "Khunjerab",
      "Attabad",
      "Shishkat",
      "Gojal",
      "Yasin",
      "Gupis",
      "Phander",
      "Teru",
      "Darkot",
      "Ishkoman",
      "Chatorkhand",
      "Imit",
      "Pingal",
      "Koh",
      "Juglote",
      "Darel",
      "Tangir",
      "Harban",
      "Bagrot",
      "Nomal",
      "Jutial",
      "Danyor",
      "Barmas",
      "Danyore",
    ],
  },
  Jordan: {
    "Amman Governorate": [
      "Amman",
      "Sahab",
      "Al-Jubayhah",
      "Marka",
      "Na'ur",
      "Wadi Sir",
      "Sweileh",
      "Badr Al Jadidah",
      "Al Jiza",
      "Muwaqqar",
      "Al Qastal",
      "Yadudah",
      "Umm Nuwara",
      "Umm al-Basatin",
      "Khreibet al-Souq",
      "Al-Hashmi",
      "Zarqa Maa",
      "Russeifa North",
      "Mahatta",
      "Hay Nazzal",
      "Abu Nsair",
      "Khalda",
      "Tlaa Al Ali",
      "Shmeisani",
      "Abdoun",
      "Rabieh",
      "Tabarbour",
      "Hay al-Hussain",
      "Dahiyat al-Rashid",
      "Marj al-Hamam",
      "Al-Urdon",
      "Jabal Amman",
      "Jabal al-Weibdeh",
      "Jabal Hussein",
      "Ras al-Ain",
      "Um Uthaina",
      "Dahiet Al Rasheed",
    ],
    "Zarqa Governorate": [
      "Zarqa",
      "Russeifa",
      "Hashimiyya",
      "Azraq",
      "Hallabat",
      "Dhuleil",
      "Sukhneh",
      "Baq'a",
      "Khaw Khaw",
      "Al-Muwaqqar",
      "Wadi Dhuleil",
      "Al-Manara",
      "Al-Ghrouf",
      "Qasabet Zarqa",
      "New Zarqa",
      "Al-Zarqa Al-Jadidah",
    ],
    "Irbid Governorate": [
      "Irbid",
      "Ramtha",
      "Al-Husn",
      "Beit Ras",
      "Koura",
      "Turra",
      "Shajara",
      "Maru",
      "Aydoun",
      "Zubia",
      "Sama Al-Sarhan",
      "Rehaba",
      "Umm Qais",
      "Abila",
      "Hartha",
      "Saham",
      "Tibne",
      "Mughier",
      "Kufr Yuba",
      "Kufr Awan",
      "Kufr Asad",
      "Bani Kinanah",
      "Kafranjeh",
      "Wadi Al-Arab",
      "Al-Mazaar al-Shamali",
      "Al-Taybeh",
      "Deir Abi Said",
      "Hatim",
      "Sakhrah",
    ],
    "Aqaba Governorate": [
      "Aqaba",
      "Quwayra",
      "Wadi Rum",
      "Disi",
      "Mudawwara",
      "Ras al-Naqab",
      "Bayir",
      "Al-Shawbak (partial)",
      "Humayma",
      "Gharandal",
      "Yutm",
      "Al-Durra",
    ],
    "Madaba Governorate": [
      "Madaba",
      "Dhiban",
      "Libb",
      "Ma'in",
      "Naur",
      "Jiza",
      "Mount Nebo",
      "Mkawer",
      "Hammamat Ma'in",
      "Faisaliyya",
      "Al-Yadudah",
      "Umm al-Walid",
      "Al-Msheirfeh",
    ],
    "Balqa Governorate": [
      "Salt",
      "Fuheis",
      "Mahis",
      "Shuna Shamaliyya",
      "Deir Alla",
      "Dayr Abu Said",
      "South Shouneh",
      "North Shouneh",
      "Zay",
      "Suweimeh",
      "Karameh",
      "Al-Mashari'",
      "Rama",
      "Shu'nat Nimrin",
      "Allan",
      "Umm al-Amad",
      "Baqoura",
      "Umm Qusayr",
      "Natifa",
    ],
    "Jerash Governorate": [
      "Jerash",
      "Sakib",
      "Kufr Rahta",
      "Mastaba",
      "Burm",
      "Souf",
      "Rajm Umm Basila",
      "Kufr Khall",
      "Suf",
      "Tibna",
      "Ayn Janna",
      "Kufr Sawm",
      "Bait Ilas",
    ],
    "Ajloun Governorate": [
      "Ajloun",
      "Kufranjah",
      "Halawa",
      "Anjara",
      "Sakhra",
      "Orjan",
      "Ayn Janna",
      "Rasun",
      "Kufr Rakeb",
      "Yabla",
      "Ibbin",
      "Ashtafiena",
      "Khreibeh",
    ],
    "Karak Governorate": [
      "Karak",
      "Al-Qatrana",
      "Mazar",
      "Mu'tah",
      "Safi",
      "Adir",
      "Al-Rabba",
      "Ader",
      "Smakieh",
      "Thaniyyat",
      "Faqou",
      "Khilda",
      "Al-Mazar al-Janubi",
      "Ghor al-Safi",
      "Lajoun",
      "Mahu",
      "Iraq al-Amir",
      "Dimneh",
    ],
    "Ma'an Governorate": [
      "Ma'an",
      "Wadi Musa",
      "Shoubak",
      "Husseiniyya",
      "Qadisiyya",
      "Ras al-Naqab",
      "Al-Jafr",
      "Batr",
      "Udruh",
      "Rajif",
      "Taybeh",
      "Dlagha",
      "Sela",
    ],
    "Mafraq Governorate": [
      "Mafraq",
      "Ruwaished",
      "Safawi",
      "Badia Shamaliyya",
      "Sama Al-Sarhan",
      "Rhab",
      "North Badia",
      "Umm al-Jimal",
      "Zaatari",
      "Ibtah",
      "Khalidiyya",
      "Dayr al-Kahf",
      "Umm al-Quttayn",
      "Hamra",
      "Abu Alanda",
      "Sarhan",
      "Manshiyya",
    ],
    "Tafilah Governorate": [
      "Tafilah",
      "Busayra",
      "Hasa",
      "Qadisiyya",
      "Ayn al-Baida",
      "Ghweir",
      "Dana",
      "Jurf ad Darawish",
      "Sela",
      "Al-Arees",
      "Mansoura",
      "Khreibet Ghazaleh",
    ],
  },
};

/**
 * Governates (Jordan) or provinces (Pakistan) for the city/province pickers.
 * Use this so the list is never built via fragile index chains.
 */
export function getProvinceOrGovernorateOptions(country: CountryName): {
  label: string;
  value: ProvinceName;
}[] {
  if (country === "Pakistan") {
    return (Object.keys(LOCATION_DATA.Pakistan) as PakistanProvinceName[]).map(
      (name) => ({ label: name, value: name as ProvinceName })
    );
  }
  return (Object.keys(LOCATION_DATA.Jordan) as JordanProvinceName[]).map(
    (name) => ({ label: name, value: name as ProvinceName })
  );
}

/**
 * Map API/legacy province or governorate strings to keys in `LOCATION_DATA[country]`.
 * Handles exact match, case-insensitive match, and short names like "Amman" → "Amman Governorate" (Jordan).
 */
export function resolveProvinceKey(
  country: CountryName,
  raw: string | null | undefined
): ProvinceName | null {
  const t = normalizeLocationString(String(raw));
  if (!t) {
    return null;
  }
  if (country === "Pakistan") {
    const map = LOCATION_DATA.Pakistan;
    const keys = Object.keys(map) as PakistanProvinceName[];
    if (t in map) {
      return t as ProvinceName;
    }
    const byCi = keys.find((k) => k.toLowerCase() === t.toLowerCase());
    return (byCi ?? null) as ProvinceName | null;
  }
  const map = LOCATION_DATA.Jordan;
  const keys = Object.keys(map) as JordanProvinceName[];
  if (t in map) {
    return t as ProvinceName;
  }
  const byCi = keys.find((k) => k.toLowerCase() === t.toLowerCase());
  if (byCi) {
    return byCi;
  }
  const byPrefix = keys.find(
    (k) =>
      k.toLowerCase().startsWith(t.toLowerCase()) ||
      k.toLowerCase().split(" ")[0] === t.toLowerCase()
  );
  return (byPrefix ?? null) as ProvinceName | null;
}
