import { StyleSheet } from "react-native";
import { moderateScale } from "react-native-size-matters";
import {
  CARD_SHADOW,
  fonts,
  fontSizes,
  colors as constantColors,
  getSheetModalHeaderContainerStyle,
  getSheetModalTitleTypography,
} from "@/shared/constants";
import { useColors } from "@/shared/theme";

export const getStyles = (colors: ReturnType<typeof useColors>) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    header: {
      paddingTop: moderateScale(16),
      paddingHorizontal: moderateScale(16),
      paddingBottom: moderateScale(12),
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    headerTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: fontSizes.h4,
      fontFamily: fonts.heading,
      color: colors.text,
    },
    headerIconSpacer: {
      width: moderateScale(24),
      height: moderateScale(24),
    },
    walletTopCluster: {
      paddingHorizontal: moderateScale(16),
      paddingTop: 0,
      paddingBottom: moderateScale(12),
    },
    fixedSummaryCardsWrapper: {
      paddingHorizontal: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
    summaryCardsRow: {
      flexDirection: "row",
      alignItems: "stretch",
      justifyContent: "space-between",
      gap: moderateScale(8),
      marginBottom: moderateScale(0),
    },
    summaryCard: {
      flex: 1,
      minWidth: 0,
      minHeight: moderateScale(80),
      borderRadius: moderateScale(12),
      backgroundColor: colors.inputBackground,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: moderateScale(12),
      paddingHorizontal: moderateScale(6),
    },
    summaryCardLabelWrapper: {
      width: "100%",
      minHeight: moderateScale(32),
      justifyContent: "center",
      marginBottom: moderateScale(6),
    },
    summaryCardLabel: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.textSecondary,
      textAlign: "center",
      width: "100%",
    },
    summaryCardAmountWrapper: {
      width: "100%",
      minHeight: moderateScale(28),
      justifyContent: "center",
      alignItems: "center",
    },
    summaryCardAmount: {
      fontSize: fontSizes.h5,
      fontFamily: fonts.heading,
      color: colors.text,
      textAlign: "center",
      width: "100%",
    },
    summaryCardAmountNegative: {
      color: colors.primary,
    },
    balanceCardWrapper: {
      paddingHorizontal: moderateScale(16),
    },
    balanceCard: {
      borderRadius: moderateScale(16),
      backgroundColor: colors.card,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingVertical: moderateScale(15),
      paddingHorizontal: moderateScale(16),
      shadowColor: colors.shadow,
      ...CARD_SHADOW,
      alignItems: "center",
    },
    balanceLabel: {
      fontSize: fontSizes.h5,
      fontFamily: fonts.heading,
      color: colors.textSecondary,
      marginBottom: moderateScale(6),
    },
    balanceAmount: {
      fontSize: fontSizes.h3,
      fontFamily: fonts.heading,
      color: colors.primary,
    },
    sectionHeader: {
      paddingHorizontal: moderateScale(16),
      paddingTop: moderateScale(6),
      paddingBottom: moderateScale(8),
    },
    subHeaderContainer: {
      paddingHorizontal: 0,
      paddingVertical: 0,
      marginHorizontal: -moderateScale(15),
    },
    sectionTitle: {
      fontSize: fontSizes.h5,
      fontFamily: fonts.heading,
      color: constantColors.primaryRed,
    },
    filterRowScroll: {
      flexGrow: 0,
      marginHorizontal: -moderateScale(16),
      marginBottom: moderateScale(8),
    },
    filterRowContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateScale(8),
      paddingHorizontal: moderateScale(16),
      paddingBottom: moderateScale(8),
    },
    filterChip: {
      flexShrink: 0,
      paddingHorizontal: moderateScale(16),
      paddingVertical: moderateScale(6),
      borderRadius: moderateScale(20),
      backgroundColor: colors.inputBackground,
    },
    filterChipActive: {
      backgroundColor: constantColors.primaryRed,
    },
    filterChipText: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.textSecondary,
    },
    filterChipTextActive: {
      color: colors.white,
    },
    walletFlatList: {
      flex: 1,
    },
    listContent: {
      paddingHorizontal: moderateScale(16),
      paddingBottom: moderateScale(24),
    },
    listContentFlex: {
      flexGrow: 1,
    },
    // Wallet transaction card – match Figma; border + theme shadow for dark mode
    transactionCard: {
      backgroundColor: colors.inputBackground,
      borderRadius: moderateScale(18),
      paddingVertical: moderateScale(18),
      paddingHorizontal: moderateScale(20),
      marginBottom: moderateScale(12),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    transactionTopRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    rejectionSection: {
      marginTop: moderateScale(12),
      paddingTop: moderateScale(12),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },

    transactionTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      flexShrink: 1,
      maxWidth: "70%",
      gap: moderateScale(8),
      marginTop: -moderateScale(8),
    },
    transactionInfo: {
      flexShrink: 1,
      minWidth: 0,
    },
    transRow: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      gap: moderateScale(8),
    },
    transactionSpacer: {
      flex: 1,
      minWidth: moderateScale(8),
    },
    transactionTitle: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.text,
      marginBottom: 0,
    },
    transactionMetaSection: {
      marginTop: moderateScale(6),
      alignSelf: "stretch",
      width: "100%",
    },
    transactionMetaFirst: {
      marginTop: 0,
    },
    transactionMeta: {
      fontSize: fontSizes.p,
      fontFamily: fonts.subTitle,
      color: colors.textSecondary,
      marginTop: moderateScale(6),
    },
    transactionAmountRow: {
      alignItems: "flex-end",
      justifyContent: "space-between",
      flexDirection: "column",
      gap: moderateScale(6),
    },
    transactionAmount: {
      fontSize: fontSizes.h6,
      fontFamily: fonts.heading,
      color: colors.primary,
    },
    transactionChevron: {
      marginTop: moderateScale(4),
      alignSelf: "flex-end",
    },
    transactionChevronInline: {
      marginTop: 0,
    },
    transactionRightSection: {
      flexDirection: "column",
      alignItems: "flex-end",
      justifyContent: "space-between",
      flexShrink: 0,
    },
    transactionRightTop: {
      flexDirection: "row",
      alignItems: "center",
      gap: moderateScale(8),
      marginBottom: moderateScale(6),
    },
    statusPillPending: {
      paddingHorizontal: moderateScale(10),
      paddingVertical: moderateScale(4),
      borderRadius: moderateScale(20),
      backgroundColor: "#FEF3C7",
      flexDirection: "row",
      alignItems: "center",
      gap: moderateScale(4),
    },
    statusPillApproved: {
      paddingHorizontal: moderateScale(10),
      paddingVertical: moderateScale(4),
      borderRadius: moderateScale(20),
      backgroundColor: "#D1FAE5",
      flexDirection: "row",
      alignItems: "center",
      gap: moderateScale(4),
    },
    statusPillReject: {
      paddingHorizontal: moderateScale(10),
      paddingVertical: moderateScale(4),
      borderRadius: moderateScale(20),
      backgroundColor: "#FEE2E2",
      flexDirection: "row",
      alignItems: "center",
      gap: moderateScale(4),
    },
    statusPillTextPending: {
      fontSize: fontSizes.small,
      fontFamily: fonts.title,
      color: "#92400E",
    },
    statusPillTextApproved: {
      fontSize: fontSizes.small,
      fontFamily: fonts.title,
      color: "#065F46",
    },
    statusPillTextReject: {
      fontSize: fontSizes.small,
      fontFamily: fonts.title,
      color: "#991B1B",
    },
    rejectionReason: {
      fontSize: fontSizes.small,
      fontFamily: fonts.subTitle,
      color: colors.textSecondary,
      marginTop: moderateScale(6),
    },
    transactionMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: moderateScale(8),
      marginTop: moderateScale(6),
    },
    transactionMetaFlex: {
      flex: 1,
      marginTop: 0,
    },
    resubmitButtonInline: {
      paddingHorizontal: moderateScale(12),
      paddingVertical: moderateScale(6),
      borderRadius: moderateScale(20),
      backgroundColor: constantColors.primaryRed,
      flexShrink: 0,
    },
    resubmitButton: {
      marginTop: moderateScale(12),
      alignSelf: "flex-end",
      paddingHorizontal: moderateScale(16),
      paddingVertical: moderateScale(8),
      borderRadius: moderateScale(24),
      backgroundColor: constantColors.primaryRed,
    },
    resubmitButtonText: {
      fontSize: fontSizes.small,
      fontFamily: fonts.button,
      color: colors.white,
    },
    addCashButton: {
      paddingHorizontal: moderateScale(16),
      paddingVertical: moderateScale(8),
      borderRadius: moderateScale(20),
      marginEnd: moderateScale(5),
      backgroundColor: constantColors.primaryRed,
    },
    depositCashSection: {
      marginBottom: moderateScale(10),
    },
    depositCashShadowWrap: {
      borderRadius: moderateScale(12),
    },
    depositCashGradient: {
      borderRadius: moderateScale(12),
      overflow: "hidden",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(255, 255, 255, 0.32)",
    },
    depositCashInner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: moderateScale(10),
      paddingVertical: moderateScale(13),
      paddingHorizontal: moderateScale(20),
      minHeight: moderateScale(48),
    },
    depositCashButtonLabel: {
      fontSize: fontSizes.p,
      fontFamily: fonts.button,
      color: colors.white,
      letterSpacing: 0.3,
    },
    // Transaction details modal
    transactionModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      padding: moderateScale(20),
    },
    transactionModalHandle: {
      width: moderateScale(40),
      height: moderateScale(4),
      borderRadius: 2,
      backgroundColor: constantColors.primaryRed,
      alignSelf: "center",
      marginTop: moderateScale(12),
      marginBottom: moderateScale(8),
    },
    transactionModalWrapper: {
      paddingHorizontal: moderateScale(20),
    },
    transactionModalContent: {
      paddingTop: moderateScale(8),
      paddingBottom: moderateScale(24),
    },
    transactionModalHeader: {
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: moderateScale(12),
      position: "relative",
      ...getSheetModalHeaderContainerStyle(),
    },
    transactionModalTitle: {
      ...getSheetModalTitleTypography(),
      color: constantColors.primaryRed,
      textAlign: "center",
    },
    transactionModalStatusPillWrapper: {
      position: "absolute",
      top: 0,
      right: 0,
    },
    transactionModalAmount: {
      fontSize: fontSizes.h1,
      fontFamily: fonts.heading,
      color: colors.primary,
      marginBottom: moderateScale(16),
      textAlign: "center",
    },
    transactionModalDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginBottom: moderateScale(16),
    },
    transactionModalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: moderateScale(12),
    },
    transactionModalLabel: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.textSecondary,
      flexShrink: 0,
      marginRight: moderateScale(12),
    },
    transactionModalValue: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.text,
      flex: 1,
      flexShrink: 1,
      textAlign: "right",
    },
    transactionModalValueMultiline: {
      textAlign: "right",
    },
    transactionModalImageRow: {
      alignItems: "flex-start",
    },
    transactionModalButtonContainer: {
      paddingBottom: moderateScale(25),
    },
    transactionModalResubmitButton: {
      width: "100%",
      paddingVertical: moderateScale(12),
      borderRadius: moderateScale(24),
      backgroundColor: constantColors.primaryRed,
      alignItems: "center",
      justifyContent: "center",
    },
    transactionModalResubmitText: {
      fontSize: fontSizes.p,
      fontFamily: fonts.button,
      color: colors.white,
    },
    transactionModalImage: {
      width: moderateScale(60),
      height: moderateScale(60),
      borderRadius: moderateScale(8),
      borderWidth: moderateScale(1),
      borderColor: colors.black,
    },

    // Bottom sheet
    sheetContainer: {
      paddingHorizontal: moderateScale(20),
      paddingBottom: moderateScale(36),
      ...getSheetModalHeaderContainerStyle(),
    },
    sheetHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: moderateScale(16),
    },
    sheetTitle: {
      ...getSheetModalTitleTypography(),
      color: colors.primary,
    },
    statusPill: {
      paddingHorizontal: moderateScale(12),
      paddingVertical: moderateScale(4),
      borderRadius: moderateScale(20),
      backgroundColor: colors.inputBackground,
    },
    statusText: {
      fontSize: fontSizes.small,
      fontFamily: fonts.title,
      color: colors.textSecondary,
    },
    customerRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: moderateScale(16),
    },
    avatar: {
      width: moderateScale(48),
      height: moderateScale(48),
      borderRadius: moderateScale(24),
      backgroundColor: colors.inputBackground,
      marginRight: moderateScale(12),
    },
    customerInfo: {
      flex: 1,
    },
    customerName: {
      fontSize: fontSizes.h5,
      fontFamily: fonts.heading,
      color: colors.text,
      marginBottom: moderateScale(6),
    },
    customerText: {
      fontSize: fontSizes.small,
      fontFamily: fonts.title,
      color: colors.textSecondary,
    },
    buttonGroup: {
      marginTop: moderateScale(12),
      gap: moderateScale(14),
    },
    // Accordion cards inside bottom sheet; border + theme shadow for dark mode
    accordionCard: {
      borderRadius: moderateScale(18),
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingHorizontal: moderateScale(18),
      paddingTop: moderateScale(14),
      paddingBottom: moderateScale(16),
      shadowColor: colors.shadow,
      ...CARD_SHADOW,
      marginBottom: moderateScale(8),
    },
    accordionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: moderateScale(8),
    },
    accordionTitle: {
      fontSize: fontSizes.h5,
      fontFamily: fonts.heading,
      color: constantColors.primaryRed,
    },
    accordionChevron: {
      marginLeft: moderateScale(8),
    },
    accordionStatusPill: {
      paddingHorizontal: moderateScale(12),
      paddingVertical: moderateScale(4),
      borderRadius: moderateScale(16),
      backgroundColor: colors.inputBackground,
    },
    accordionStatusText: {
      fontSize: fontSizes.small,
      fontFamily: fonts.title,
      color: colors.textSecondary,
    },
    accordionContent: {
      paddingTop: moderateScale(4),
    },
    infoRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: moderateScale(10),
    },
    infoIcon: {
      width: moderateScale(24),
      alignItems: "center",
      marginRight: moderateScale(10),
      paddingTop: moderateScale(2),
    },
    infoTextContainer: {
      flex: 1,
    },
    infoLabel: {
      fontSize: fontSizes.small,
      fontFamily: fonts.title,
      color: colors.textSecondary,
      marginBottom: moderateScale(2),
    },
    sheetCashDepositError: {
      fontSize: fontSizes.small,
      fontFamily: fonts.title,
      color: colors.red,
      marginTop: moderateScale(4),
      marginBottom: moderateScale(8),
    },
    sheetCashDepositInputError: {
      borderColor: constantColors.red,
    },
    infoValue: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.text,
    },
    itemsHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: moderateScale(6),
    },
    itemsLabel: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.text,
    },
    itemsAmount: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.primary,
      fontWeight: "600",
    },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginVertical: moderateScale(8),
    },
    totalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: moderateScale(2),
    },
    totalLabel: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.text,
    },
    totalValue: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.primary,
      fontWeight: "600",
    },
    // Cash flow upload rectangle (cash slip) – match stepper upload design
    cashSlipBox: {
      marginTop: moderateScale(10),
      marginBottom: moderateScale(16),
      height: moderateScale(200),
      borderRadius: moderateScale(8),
      borderWidth: moderateScale(1),
      borderStyle: "dashed",
      borderColor: colors.textSecondary,
      backgroundColor: colors.white,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    cashSlipPlaceholderText: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.textSecondary,
      textAlign: "center",
      paddingHorizontal: moderateScale(16),
    },
    cashSlipImage: {
      width: "100%",
      height: "100%",
      borderRadius: moderateScale(8),
    },
    cashSlipLoadingOverlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: "rgba(255, 255, 255, 0.82)",
      justifyContent: "center",
      alignItems: "center",
      gap: moderateScale(10),
      borderRadius: moderateScale(8),
    },
    cashSlipLoadingText: {
      fontSize: fontSizes.p,
      fontFamily: fonts.title,
      color: colors.textSecondary,
      textAlign: "center",
    },
    sheetButtonsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: moderateScale(20),
      columnGap: moderateScale(12),
    },
    sheetCancelButton: {
      flex: 1,
      height: moderateScale(44),
      borderRadius: moderateScale(24),
      borderWidth: moderateScale(1),
      borderColor: constantColors.primaryRed,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.white,
    },
    sheetCancelText: {
      fontSize: fontSizes.p,
      fontFamily: fonts.button,
      color: constantColors.primaryRed,
    },
    sheetPrimaryButton: {
      flex: 1,
      height: moderateScale(42),
      justifyContent: "center",
      borderRadius: moderateScale(24),
    },
  });
