stages:
  - comment

include:
  - project: 'DevSoul/devops-templates'
    file:
      - '/ci/comment-job.yml'

# Job that runs and extends the MR comment template
comment-on-mr-job:
  extends: .comment-on-mr
  tags:
    - dokploy-local
